# Generated by Django 4.0.5 on 2022-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_about_options_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='select',
            field=models.CharField(choices=[('Велосипеды', 'Велосипеды'), ('Электросамокаты', 'Электросамокаты')], max_length=15, verbose_name='Choose category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Types of vehicle'),
        ),
    ]
